"use client";
/* eslint-disable @next/next/no-html-link-for-pages, react-hooks/set-state-in-effect */

import { FormEvent, useEffect, useMemo, useState } from "react";
import { ArrowLeft, BarChart3, Bell, Box, Check, CircleUserRound, Download, LayoutDashboard, LogOut, Package, Pencil, Plus, Search, Settings, ShoppingBag, SlidersHorizontal, Tag, Trash2, Users, X, Zap } from "lucide-react";
import { usePathname, useRouter } from "next/navigation";

type AdminProduct = { id: number; name: string; sku: string; category: string; source: string; price: number; stock: number; status: string };
type AdminOrder = { id: string; customer: string; date: string; total: string; status: string };

const seedProducts: AdminProduct[] = [
  { id: 1, name: "سماعات لاسلكية Auralite", sku: "NV-AUR-001", category: "إلكترونيات", source: "MediaMarkt · ألمانيا", price: 49, stock: 8, status: "متوفر" },
  { id: 2, name: "مصباح طاولة نوردك", sku: "NV-NOR-002", category: "المنزل", source: "IKEA Europe · السويد", price: 34, stock: 14, status: "متوفر" },
  { id: 3, name: "حقيبة ظهر Urban Line", sku: "NV-URB-003", category: "أزياء", source: "Zalando · ألمانيا", price: 58, stock: 5, status: "منخفض" },
  { id: 4, name: "طقم عناية بالبشرة Lumina", sku: "NV-LUM-004", category: "العناية", source: "Douglas · فرنسا", price: 41, stock: 19, status: "متوفر" },
];
const seedOrders: AdminOrder[] = [
  { id: "NV-1048", customer: "ليان أحمد", date: "06 أغسطس 2026", total: "132 €", status: "قيد المعالجة" },
  { id: "NV-1047", customer: "عمر خليل", date: "06 أغسطس 2026", total: "76 €", status: "تم الشحن" },
  { id: "NV-1046", customer: "سارة يوسف", date: "05 أغسطس 2026", total: "214 €", status: "مكتمل" },
  { id: "NV-1045", customer: "محمد حسان", date: "05 أغسطس 2026", total: "49 €", status: "مكتمل" },
];
const nav = [["لوحة المعلومات", "/admin", LayoutDashboard], ["المنتجات", "/admin/products", Package], ["الأقسام", "/admin/categories", Tag], ["الطلبات", "/admin/orders", ShoppingBag], ["المخزون", "/admin/inventory", Box], ["العروض", "/admin/promotions", Tag], ["العملاء", "/admin/customers", Users], ["التقارير", "/admin/reports", BarChart3], ["الإعدادات", "/admin/settings", Settings]] as const;

function AdminLogin({ onSuccess }: { onSuccess: () => void }) {
  const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [error, setError] = useState("");
  const submit = (event: FormEvent) => { event.preventDefault(); if (email.toLowerCase() === "admin@nova.store" && password === "admin123") { localStorage.setItem("nova-admin-auth", "1"); onSuccess(); } else setError("بيانات المدير التجريبية: admin@nova.store / admin123"); };
  return <main className="login-page content-layer"><div className="panel login-box"><a href="/" className="brand"><span className="brand-mark"><Zap size={17} fill="currentColor" /></span><strong>NOVA</strong><span>ADMIN</span></a><h1>دخول المدير</h1><p>أدخل بيانات مدير المتجر للوصول إلى أدوات الإدارة.</p><form className="login-form" onSubmit={submit}><input className="form-control" type="email" required placeholder="البريد الإلكتروني" value={email} onChange={e => setEmail(e.target.value)} /><input className="form-control" type="password" required placeholder="كلمة المرور" value={password} onChange={e => setPassword(e.target.value)} />{error && <div style={{ color: "#fbbf24", fontSize: 12 }}>{error}</div>}<button className="primary-btn" type="submit">دخول لوحة الإدارة <ArrowLeft size={17} /></button></form><p className="hint">هذه مصادقة تجريبية محلية فقط، وستُستبدل بمصادقة الخادم عند إضافة backend.</p></div></main>;
}

function AdminShell({ children, onLogout }: { children: React.ReactNode; onLogout: () => void }) { const pathname = usePathname(); const router = useRouter(); return <div className="admin-shell content-layer"><aside className="admin-sidebar"><div className="admin-brand"><a href="/" className="brand"><span className="brand-mark"><Zap size={17} fill="currentColor" /></span><strong>NOVA</strong><span>ADMIN</span></a></div><nav className="admin-nav">{nav.map(([label, href, Icon]) => <a className={pathname === href ? "active" : ""} href={href} key={href}><Icon size={18} />{label}</a>)}</nav><button className="secondary-btn" style={{ width: "100%", marginTop: 28 }} onClick={() => router.push("/")}><ArrowLeft size={16} /> العودة للمتجر</button><button className="secondary-btn" style={{ width: "100%", marginTop: 10 }} onClick={onLogout}><LogOut size={16} /> تسجيل الخروج</button></aside><section className="admin-main"><header className="admin-header"><div className="eyebrow" style={{ margin: 0 }}>مساحة الإدارة · مدير المتجر</div><div style={{ display: "flex", gap: 8 }}><button className="icon-btn" aria-label="الإشعارات"><Bell size={18} /></button><button className="avatar-btn" aria-label="حساب المدير"><CircleUserRound size={20} /></button></div></header>{children}</section></div>; }

function Title({ title, note, action }: { title: string; note: string; action?: React.ReactNode }) { return <div className="admin-title"><div><h1>{title}</h1><p>{note}</p></div>{action}</div>; }
function Status({ value }: { value: string }) { return <span className={`status ${value === "متوفر" || value === "مكتمل" ? "status-green" : "status-orange"}`}>{value}</span>; }

function Dashboard() { const bars = [43, 62, 55, 76, 50, 83, 66, 91, 70, 87, 76, 95, 72, 84, 60, 78, 92, 88, 94, 81]; return <div className="admin-content"><Title title="لوحة المعلومات" note="نظرة سريعة على أداء متجرك اليوم." action={<a className="primary-btn" href="/admin/products/new"><Plus size={17} /> منتج جديد</a>} /><div className="kpi-grid"><div className="panel kpi"><div className="kpi-label">مبيعات اليوم</div><div className="kpi-value">2,840 €</div><div className="kpi-change">↑ 18.4% عن الأمس</div></div><div className="panel kpi"><div className="kpi-label">إجمالي الطلبات</div><div className="kpi-value">128</div><div className="kpi-change">↑ 12.6% هذا الشهر</div></div><div className="panel kpi"><div className="kpi-label">متوسط السلة</div><div className="kpi-value">64 €</div><div className="kpi-change">↑ 8.2% عن الأسبوع</div></div><div className="panel kpi"><div className="kpi-label">عملاء جدد</div><div className="kpi-value">46</div><div className="kpi-change">↑ 21.5% هذا الأسبوع</div></div></div><div className="admin-grid"><div className="panel"><h3>المبيعات خلال 30 يوماً</h3><div className="chart">{bars.map((height, index) => <span className="bar" style={{ "--height": `${height}%` } as React.CSSProperties} key={index} />)}</div></div><div className="panel"><h3>تنبيهات المخزون</h3><div className="empty" style={{ padding: "28px 10px" }}>كل المنتجات فوق حد المخزون المنخفض.</div></div></div></div>; }

function ProductForm({ editId }: { editId?: string }) { const router = useRouter(); const existing = seedProducts.find(p => String(p.id) === editId); const [saved, setSaved] = useState(false); const save = (event: FormEvent) => { event.preventDefault(); setSaved(true); setTimeout(() => router.push("/admin/products"), 700); }; return <div className="admin-content"><Title title={existing ? "تعديل المنتج" : "إضافة منتج جديد"} note="أدخل بيانات المنتج ومصدره الأوروبي ليظهر في المتجر." action={<button className="secondary-btn" onClick={() => router.push("/admin/products")}><X size={16} /> إلغاء</button>} /><form className="panel" onSubmit={save}><div className="form-grid"><div className="form-group"><label>اسم المنتج</label><input className="form-control" required defaultValue={existing?.name} placeholder="مثال: سماعات لاسلكية" /></div><div className="form-group"><label>رمز المنتج SKU</label><input className="form-control" required defaultValue={existing?.sku} placeholder="NV-NEW-001" /></div><div className="form-group"><label>القسم</label><select className="form-control" defaultValue={existing?.category || "إلكترونيات"}><option>إلكترونيات</option><option>المنزل</option><option>أزياء</option><option>العناية</option><option>أطفال</option><option>رياضة</option></select></div><div className="form-group"><label>العلامة / المورد الأوروبي</label><input className="form-control" required defaultValue={existing?.source} placeholder="اسم المتجر · الدولة" /></div><div className="form-group"><label>السعر (€)</label><input className="form-control" type="number" min="0" required defaultValue={existing?.price} /></div><div className="form-group"><label>الكمية</label><input className="form-control" type="number" min="0" required defaultValue={existing?.stock} /></div><div className="form-group full"><label>وصف المنتج</label><textarea className="form-control" placeholder="اكتب وصفاً واضحاً للمنتج ومزاياه." defaultValue="منتج أوروبي أصلي يصل إليك جديداً بعلبته." /></div><div className="form-group full"><label>صور المنتج</label><div className="empty" style={{ padding: "26px" }}>اسحب الصور هنا أو اضغط لاختيار صور (رفع تجريبي محلي)</div></div></div><div className="actions" style={{ marginTop: 24 }}><button type="submit" className="primary-btn">{saved ? <><Check size={17} /> تم الحفظ</> : <><Check size={17} /> حفظ المنتج</>}</button><button type="button" className="secondary-btn" onClick={() => router.push("/admin/products")}>حفظ كمسودة</button></div></form></div>; }

function ProductsPage() { const router = useRouter(); const [query, setQuery] = useState(""); const [rows, setRows] = useState(seedProducts); const filtered = useMemo(() => rows.filter(p => `${p.name} ${p.sku} ${p.category}`.toLowerCase().includes(query.toLowerCase())), [query, rows]); const remove = (id: number) => setRows(items => items.filter(item => item.id !== id)); return <div className="admin-content"><Title title="المنتجات" note="إضافة وتعديل المنتجات ومصادرها الأوروبية من مكان واحد." action={<button className="primary-btn" onClick={() => router.push("/admin/products/new")}><Plus size={17} /> منتج جديد</button>} /><div className="panel"><div className="toolbar"><div className="toolbar-group"><div style={{ position: "relative" }}><Search size={16} style={{ position: "absolute", top: 14, right: 12, color: "var(--muted)" }} /><input className="field" style={{ paddingRight: 38 }} placeholder="ابحث بالاسم أو SKU" value={query} onChange={e => setQuery(e.target.value)} /></div><button className="secondary-btn"><SlidersHorizontal size={16} /> تصفية</button></div><span style={{ color: "var(--muted)", fontSize: 13 }}>{filtered.length} منتجات</span></div><div className="table-wrap"><table><thead><tr><th>المنتج</th><th>SKU</th><th>القسم</th><th>المصدر</th><th>السعر</th><th>المخزون</th><th>الحالة</th><th>إجراءات</th></tr></thead><tbody>{filtered.map(product => <tr key={product.id}><td>{product.name}</td><td className="font-orbitron">{product.sku}</td><td>{product.category}</td><td>{product.source}</td><td>{product.price} €</td><td>{product.stock}</td><td><Status value={product.status} /></td><td><button className="icon-btn" style={{ width: 34, height: 34 }} onClick={() => router.push(`/admin/products/${product.id}/edit`)} aria-label="تعديل"><Pencil size={15} /></button><button className="icon-btn" style={{ width: 34, height: 34 }} onClick={() => remove(product.id)} aria-label="حذف"><Trash2 size={15} /></button></td></tr>)}</tbody></table></div></div></div>; }

function OrdersPage() { const router = useRouter(); return <div className="admin-content"><Title title="الطلبات" note="راجع الطلبات وحدّث حالتها وتابع رحلة الشحن." /><div className="panel"><div className="toolbar"><div className="toolbar-group"><button className="secondary-btn"><SlidersHorizontal size={16} /> الحالة</button><button className="secondary-btn"><Search size={16} /> بحث</button></div><button className="secondary-btn" onClick={() => alert("تم تجهيز تقرير الطلبات للتصدير") }><Download size={16} /> تصدير</button></div><div className="table-wrap"><table><thead><tr><th>الطلب</th><th>العميل</th><th>التاريخ</th><th>الإجمالي</th><th>الحالة</th><th>إجراء</th></tr></thead><tbody>{seedOrders.map(order => <tr key={order.id}><td className="font-orbitron">{order.id}</td><td>{order.customer}</td><td>{order.date}</td><td>{order.total}</td><td><Status value={order.status} /></td><td><button className="secondary-btn" style={{ minHeight: 34, padding: "0 10px", fontSize: 12 }} onClick={() => router.push(`/admin/orders/${order.id}`)}>عرض وتحديث</button></td></tr>)}</tbody></table></div></div></div>; }

function InventoryPage() { const [editing, setEditing] = useState(false); const [saved, setSaved] = useState(false); return <div className="admin-content"><Title title="إدارة المخزون" note="تابع الكميات، واضبط أي حركة مع سبب واضح." action={<button className="primary-btn" onClick={() => setEditing(true)}><Plus size={17} /> تعديل كمية</button>} />{editing && <div className="panel" style={{ marginBottom: 18 }}><div className="form-grid"><div className="form-group"><label>المنتج</label><select className="form-control"><option>سماعات لاسلكية Auralite</option><option>حقيبة ظهر Urban Line</option></select></div><div className="form-group"><label>الكمية الجديدة</label><input className="form-control" type="number" defaultValue="8" /></div><div className="form-group full"><label>سبب التعديل (إلزامي)</label><input className="form-control" required placeholder="مثال: استلام شحنة جديدة" /></div></div><div className="actions" style={{ marginTop: 17 }}><button className="primary-btn" onClick={() => { setSaved(true); setEditing(false); }}>حفظ الحركة <Check size={16} /></button><button className="secondary-btn" onClick={() => setEditing(false)}>إلغاء</button></div></div>}{saved && <div className="status status-green" style={{ marginBottom: 15 }}>تم تسجيل حركة المخزون بنجاح.</div>}<div className="panel table-wrap"><table><thead><tr><th>المنتج</th><th>الكمية الكلية</th><th>المتاح</th><th>حد التنبيه</th><th>الحالة</th><th>آخر حركة</th></tr></thead><tbody>{seedProducts.map(p => <tr key={p.id}><td>{p.name}</td><td>{p.stock + 4}</td><td>{p.stock}</td><td>5</td><td><Status value={p.stock <= 5 ? "منخفض" : "متوفر"} /></td><td>استلام شحنة · اليوم</td></tr>)}</tbody></table></div></div>; }

function PromotionsPage() { const [showForm, setShowForm] = useState(false); const [saved, setSaved] = useState(false); return <div className="admin-content"><Title title="العروض والحملات" note="أنشئ الخصومات والكوبونات والباقات التي تظهر للزبائن." action={<button className="primary-btn" onClick={() => setShowForm(true)}><Plus size={17} /> حملة جديدة</button>} />{showForm && <div className="panel" style={{ marginBottom: 18 }}><div className="form-grid"><div className="form-group"><label>اسم الحملة</label><input className="form-control" placeholder="عرض الصيف الأوروبي" /></div><div className="form-group"><label>نوع الخصم</label><select className="form-control"><option>نسبة مئوية</option><option>مبلغ ثابت</option><option>كوبون</option><option>باقة منتجات</option></select></div><div className="form-group"><label>قيمة الخصم</label><input className="form-control" type="number" placeholder="20" /></div><div className="form-group"><label>تاريخ الانتهاء</label><input className="form-control" type="date" /></div></div><div className="actions" style={{ marginTop: 17 }}><button className="primary-btn" onClick={() => { setSaved(true); setShowForm(false); }}>حفظ الحملة <Check size={16} /></button><button className="secondary-btn" onClick={() => setShowForm(false)}>إلغاء</button></div></div>}{saved && <div className="status status-green" style={{ marginBottom: 15 }}>تم إنشاء الحملة محلياً.</div>}<div className="panel table-wrap"><table><thead><tr><th>الحملة</th><th>النوع</th><th>القيمة</th><th>الاستخدام</th><th>الانتهاء</th><th>الحالة</th></tr></thead><tbody><tr><td>اختيارات الصيف</td><td>خصم نسبة</td><td>20%</td><td>84 / 200</td><td>31 أغسطس 2026</td><td><Status value="متوفر" /></td></tr><tr><td>NOVA10</td><td>كوبون</td><td>10 €</td><td>42 / 100</td><td>15 سبتمبر 2026</td><td><Status value="متوفر" /></td></tr></tbody></table></div></div>; }

function CustomersPage() { return <div className="admin-content"><Title title="العملاء" note="ملفات العملاء، الطلبات، وقيمة المشتريات." action={<button className="secondary-btn" onClick={() => alert("تم تصدير قائمة العملاء") }><Download size={16} /> تصدير العملاء</button>} /><div className="panel table-wrap"><table><thead><tr><th>العميل</th><th>البريد</th><th>الطلبات</th><th>إجمالي الإنفاق</th><th>الحالة</th><th>إجراء</th></tr></thead><tbody>{[["ليان أحمد","layan@example.com","12","620 €"],["عمر خليل","omar@example.com","8","418 €"],["سارة يوسف","sara@example.com","6","302 €"],["محمد حسان","mohammad@example.com","4","188 €"]].map(([name,email,count,total])=><tr key={email}><td>{name}</td><td>{email}</td><td>{count}</td><td>{total}</td><td><Status value="نشط" /></td><td><button className="icon-btn" style={{ width: 34, height: 34 }} aria-label="تعديل"><Pencil size={15} /></button></td></tr>)}</tbody></table></div></div>; }

function ReportsPage() { return <div className="admin-content"><Title title="التقارير" note="حلّل المبيعات حسب الفترة والقسم والمنتج." action={<button className="primary-btn" onClick={() => alert("تم تجهيز التقرير للتنزيل") }><Download size={16} /> تصدير التقرير</button>} /><div className="kpi-grid"><div className="panel kpi"><div className="kpi-label">الإيراد</div><div className="kpi-value">18,420 €</div></div><div className="panel kpi"><div className="kpi-label">الطلبات</div><div className="kpi-value">384</div></div><div className="panel kpi"><div className="kpi-label">متوسط الطلب</div><div className="kpi-value">48 €</div></div><div className="panel kpi"><div className="kpi-label">معدل التحويل</div><div className="kpi-value">6.8%</div></div></div><div className="panel"><h3>المبيعات حسب القسم</h3><div className="table-wrap"><table><thead><tr><th>القسم</th><th>الإيراد</th><th>نسبة المبيعات</th><th>النمو</th></tr></thead><tbody>{[["إلكترونيات","6,840 €","37%","+18%"],["المنزل","4,210 €","23%","+12%"],["أزياء","3,650 €","20%","+9%"],["العناية","2,940 €","16%","+24%"]].map(row=><tr key={row[0]}>{row.map(cell=><td key={cell}>{cell}</td>)}</tr>)}</tbody></table></div></div></div>; }

function SettingsPage() { const [saved, setSaved] = useState(false); return <div className="admin-content"><Title title="الإعدادات" note="بيانات المتجر، الشحن، والخيارات الافتراضية." action={<button className="primary-btn" onClick={() => setSaved(true)}><Check size={17} /> حفظ التغييرات</button>} />{saved && <div className="status status-green" style={{ marginBottom: 15 }}>تم حفظ إعدادات المتجر محلياً.</div>}<div className="panel"><div className="form-grid"><div className="form-group"><label>اسم المتجر</label><input className="form-control" defaultValue="NOVA MARKET" /></div><div className="form-group"><label>البريد الإلكتروني</label><input className="form-control" defaultValue="hello@novamarket.store" /></div><div className="form-group"><label>رقم التواصل</label><input className="form-control" defaultValue="+963 944 000 000" /></div><div className="form-group"><label>سعر الشحن الافتراضي</label><input className="form-control" defaultValue="مجاني للطلبات فوق 50 €" /></div><div className="form-group full"><label>وصف المتجر</label><textarea className="form-control" defaultValue="نختار المنتجات الأوروبية الأصلية من شركاء موثوقين ونقدمها لك بوضوح وثقة." /></div></div></div></div>; }

function OrderDetail({ id }: { id: string }) { const router = useRouter(); const [status, setStatus] = useState("قيد المعالجة"); return <div className="admin-content"><Title title={`تفاصيل الطلب ${id}`} note="تابع العناصر والعنوان وحالة التنفيذ." action={<button className="secondary-btn" onClick={() => router.push("/admin/orders")}><ArrowLeft size={16} /> العودة للطلبات</button>} /><div className="split-layout"><div className="panel"><h2>خط سير الطلب</h2>{["قيد المعالجة", "مؤكد", "تم الشحن", "تم التسليم"].map(item=><button key={item} className={status===item?"primary-btn":"secondary-btn"} style={{ width: "100%", justifyContent: "space-between", marginBottom: 9 }} onClick={() => setStatus(item)}>{item}<Check size={15} /></button>)}</div><div className="panel"><h2>ملخص العميل</h2><div className="summary-line"><span>العميل</span><b>ليان أحمد</b></div><div className="summary-line"><span>العنوان</span><b>دمشق · المزة</b></div><div className="summary-line"><span>الإجمالي</span><b>132 €</b></div><div className="summary-line"><span>الحالة الحالية</span><Status value={status} /></div></div></div></div>; }

export default function AdminPortal() { const pathname = usePathname(); const router = useRouter(); const [auth, setAuth] = useState<boolean | null>(null); useEffect(() => setAuth(localStorage.getItem("nova-admin-auth") === "1"), []); const logout = () => { localStorage.removeItem("nova-admin-auth"); setAuth(false); router.push("/admin"); }; if (auth === null) return null; if (!auth) return <AdminLogin onSuccess={() => setAuth(true)} />; const parts = pathname.split("/").filter(Boolean); const section = parts[1] || ""; const action = parts[2] || ""; let page: React.ReactNode; if (section === "" ) page = <Dashboard />; else if (section === "products" && (action === "new" || action === "edit")) page = <ProductForm editId={parts[3]} />; else if (section === "products") page = <ProductsPage />; else if (section === "orders" && action) page = <OrderDetail id={action} />; else if (section === "orders") page = <OrdersPage />; else if (section === "inventory") page = <InventoryPage />; else if (section === "promotions") page = <PromotionsPage />; else if (section === "customers") page = <CustomersPage />; else if (section === "reports") page = <ReportsPage />; else if (section === "settings") page = <SettingsPage />; else page = <Dashboard />; return <AdminShell onLogout={logout}>{page}</AdminShell>; }
