"use client";
/* eslint-disable @next/next/no-html-link-for-pages, react-hooks/set-state-in-effect */

import { useEffect, useMemo, useState } from "react";
import { BarChart3, Check, Download, Filter, Package, ShoppingBag, Tag, TrendingDown, TrendingUp, Zap } from "lucide-react";
import { useRouter } from "next/navigation";

type ReportKey = "sales" | "promotions" | "top" | "low" | "inventory" | "movement";
const reports: [ReportKey, string, typeof BarChart3][] = [["sales", "تقرير المبيعات", BarChart3], ["promotions", "تقرير العروض", Tag], ["top", "الأكثر مبيعاً", TrendingUp], ["low", "الأقل مبيعاً", TrendingDown], ["inventory", "تقرير المخزون", Package], ["movement", "حركة البيع", ShoppingBag]];
const sales = [{ day: "01 أغسطس", revenue: 820, orders: 18, average: 45.6 }, { day: "02 أغسطس", revenue: 1140, orders: 25, average: 45.6 }, { day: "03 أغسطس", revenue: 760, orders: 16, average: 47.5 }, { day: "04 أغسطس", revenue: 1480, orders: 31, average: 47.7 }, { day: "05 أغسطس", revenue: 1320, orders: 28, average: 47.1 }, { day: "06 أغسطس", revenue: 1720, orders: 36, average: 47.8 }, { day: "07 أغسطس", revenue: 1580, orders: 34, average: 46.5 }];
const best = [{ name: "سماعات لاسلكية Auralite", sku: "NV-AUR-001", sold: 84, revenue: 4116, stock: 8 }, { name: "حقيبة ظهر Urban Line", sku: "NV-URB-003", sold: 62, revenue: 3596, stock: 5 }, { name: "مصباح طاولة نوردك", sku: "NV-NOR-002", sold: 58, revenue: 1972, stock: 14 }, { name: "طقم عناية بالبشرة Lumina", sku: "NV-LUM-004", sold: 46, revenue: 1886, stock: 19 }];
const low = [{ name: "ساعة حائط Minimal", sku: "NV-MIN-008", sold: 3, revenue: 93, stock: 16 }, { name: "طقم تنظيم الأطفال MiniBox", sku: "NV-MIN-007", sold: 7, revenue: 189, stock: 9 }, { name: "حذاء رياضي Cloud Move", sku: "NV-CLO-006", sold: 11, revenue: 682, stock: 12 }, { name: "مطحنة قهوة Barista Pro", sku: "NV-BAR-005", sold: 14, revenue: 1064, stock: 3 }];
const promotions = [{ name: "اختيارات الصيف", code: "SUMMER20", type: "نسبة مئوية", value: "20%", uses: 84, revenue: 4120, status: "نشط" }, { name: "خصم الشراء الأول", code: "NOVA10", type: "مبلغ ثابت", value: "10 $", uses: 42, revenue: 1680, status: "نشط" }, { name: "باقة المنزل", code: "HOME-BUNDLE", type: "باقة", value: "15%", uses: 27, revenue: 1090, status: "منتهي" }];
const inventory = [{ name: "سماعات لاسلكية Auralite", category: "إلكترونيات", opening: 42, inbound: 20, sold: 54, available: 8, status: "مراقبة" }, { name: "مصباح طاولة نوردك", category: "المنزل", opening: 31, inbound: 12, sold: 29, available: 14, status: "جيد" }, { name: "حقيبة ظهر Urban Line", category: "أزياء", opening: 28, inbound: 8, sold: 31, available: 5, status: "منخفض" }, { name: "مطحنة قهوة Barista Pro", category: "المنزل", opening: 18, inbound: 0, sold: 15, available: 3, status: "منخفض" }];
const movement = [{ date: "07 أغسطس · 14:35", order: "NV-1048", product: "سماعات لاسلكية Auralite", quantity: 2, amount: 98, customer: "ليان أحمد", channel: "المتجر" }, { date: "07 أغسطس · 13:10", order: "NV-1047", product: "مطحنة قهوة Barista Pro", quantity: 1, amount: 76, customer: "عمر خليل", channel: "المتجر" }, { date: "06 أغسطس · 19:42", order: "NV-1046", product: "حقيبة ظهر Urban Line", quantity: 2, amount: 116, customer: "سارة يوسف", channel: "المتجر" }, { date: "06 أغسطس · 17:20", order: "NV-1045", product: "سماعات لاسلكية Auralite", quantity: 1, amount: 49, customer: "محمد حسان", channel: "المتجر" }];

function Status({ value }: { value: string }) { return <span className={`status ${value === "جيد" || value === "نشط" ? "status-green" : value === "منتهي" ? "status-pink" : "status-orange"}`}>{value}</span>; }
function Money({ value }: { value: number }) { return <span className="font-orbitron">{value.toLocaleString("en-US")} $</span>; }
function ReportHeader({ title, description, onExport }: { title: string; description: string; onExport: () => void }) { return <div className="admin-title"><div><h1>{title}</h1><p>{description}</p></div><button className="primary-btn" onClick={onExport}><Download size={16} /> تصدير التقرير</button></div>; }
function FilterBar({ onChange }: { onChange: (value: string) => void }) { return <div className="panel" style={{ marginBottom: 18, display: "flex", alignItems: "center", gap: 10, flexWrap: "wrap" }}><Filter size={17} color="var(--cyan)" /><span style={{ color: "var(--muted)", fontSize: 13 }}>الفترة:</span><select className="select" style={{ minWidth: 150 }} onChange={e => onChange(e.target.value)}><option value="week">آخر 7 أيام</option><option value="month">هذا الشهر</option><option value="quarter">آخر 3 أشهر</option></select><input className="field" type="date" aria-label="من تاريخ" /><span style={{ color: "var(--muted)" }}>إلى</span><input className="field" type="date" aria-label="إلى تاريخ" /><button className="secondary-btn" style={{ minHeight: 42 }} onClick={() => onChange("filtered")}><Check size={15} /> تطبيق</button></div>; }

function SalesReport() { const max = Math.max(...sales.map(row => row.revenue)); return <><FilterBar onChange={() => undefined} /><div className="kpi-grid"><div className="panel kpi"><div className="kpi-label">إجمالي المبيعات</div><div className="kpi-value">9,820 $</div><div className="kpi-change">↑ 14.8% عن الفترة السابقة</div></div><div className="panel kpi"><div className="kpi-label">عدد الطلبات</div><div className="kpi-value">188</div><div className="kpi-change">↑ 21 طلباً</div></div><div className="panel kpi"><div className="kpi-label">متوسط قيمة الطلب</div><div className="kpi-value">46.9 $</div><div className="kpi-change">↑ 3.2%</div></div><div className="panel kpi"><div className="kpi-label">العملاء العائدون</div><div className="kpi-value">38%</div><div className="kpi-change">↑ 6.4%</div></div></div><div className="admin-grid"><div className="panel"><h3>منحنى المبيعات اليومي</h3><div className="chart">{sales.map(row => <span className="bar" title={`${row.day}: ${row.revenue} $`} style={{ "--height": `${Math.round(row.revenue / max * 100)}%` } as React.CSSProperties} key={row.day} />)}</div></div><div className="panel"><h3>قراءة سريعة</h3><div className="summary-line"><span>أفضل يوم</span><b>04 أغسطس</b></div><div className="summary-line"><span>أعلى إيراد يومي</span><b>1,720 $</b></div><div className="summary-line"><span>نمو المبيعات</span><b style={{ color: "#63e6be" }}>+14.8%</b></div></div></div><div className="panel table-wrap"><h3>تفصيل المبيعات حسب اليوم</h3><table><thead><tr><th>اليوم</th><th>الإيراد</th><th>الطلبات</th><th>متوسط الطلب</th><th>مقارنة</th></tr></thead><tbody>{sales.map((row, index) => <tr key={row.day}><td>{row.day}</td><td><Money value={row.revenue} /></td><td>{row.orders}</td><td><Money value={row.average} /></td><td><span className="status status-green">{index === 0 ? "بداية الفترة" : `+${index * 2 + 4}%`}</span></td></tr>)}</tbody></table></div></>; }

function PromotionsReport() { return <><FilterBar onChange={() => undefined} /><div className="panel table-wrap"><h3>أداء العروض والكوبونات</h3><table><thead><tr><th>الحملة</th><th>الكود</th><th>النوع</th><th>القيمة</th><th>الاستخدام</th><th>الإيراد الناتج</th><th>الحالة</th></tr></thead><tbody>{promotions.map(row => <tr key={row.code}><td>{row.name}</td><td className="font-orbitron">{row.code}</td><td>{row.type}</td><td>{row.value}</td><td>{row.uses}</td><td><Money value={row.revenue} /></td><td><Status value={row.status} /></td></tr>)}</tbody></table></div><div className="admin-grid" style={{ marginTop: 18 }}><div className="panel"><h3>تكلفة الخصومات</h3><div className="summary-line"><span>إجمالي الخصومات</span><b>1,284 $</b></div><div className="summary-line"><span>الإيراد بعد الخصم</span><b>6,890 $</b></div><div className="summary-line"><span>العائد على الحملة</span><b style={{ color: "#63e6be" }}>5.36x</b></div></div><div className="panel"><h3>أفضل حملة</h3><p style={{ fontSize: 24, margin: "10px 0", color: "var(--cyan)" }}>اختيارات الصيف</p><p style={{ color: "var(--muted)" }}>84 استخداماً · 4,120 $ مبيعات مرتبطة</p></div></div></>; }

function ProductRankReport({ direction }: { direction: "top" | "low" }) { const rows = direction === "top" ? best : low; return <><FilterBar onChange={() => undefined} /><div className="panel table-wrap"><h3>{direction === "top" ? "المنتجات الأكثر مبيعاً" : "المنتجات الأقل مبيعاً"}</h3><table><thead><tr><th>#</th><th>المنتج</th><th>SKU</th><th>الوحدات المباعة</th><th>الإيراد</th><th>المخزون الحالي</th><th>الإجراء المقترح</th></tr></thead><tbody>{rows.map((row, index) => <tr key={row.sku}><td className="font-orbitron">{index + 1}</td><td>{row.name}</td><td className="font-orbitron">{row.sku}</td><td>{row.sold}</td><td><Money value={row.revenue} /></td><td>{row.stock}</td><td><Status value={direction === "top" && row.stock <= 5 ? "إعادة طلب" : direction === "top" ? "استمر" : "مراجعة العرض"} /></td></tr>)}</tbody></table></div><div className="panel" style={{ marginTop: 18 }}><h3>ملاحظة تحليلية</h3><p style={{ color: "var(--muted)", margin: 0 }}>{direction === "top" ? "هذه المنتجات تقود الإيراد الحالي. راقب المخزون المنخفض قبل إطلاق حملة جديدة عليها." : "المنتجات الأقل مبيعاً تحتاج مراجعة السعر أو الوصف أو موضعها في المتجر قبل زيادة المخزون."}</p></div></>; }

function InventoryReport() { return <><FilterBar onChange={() => undefined} /><div className="panel table-wrap"><h3>حالة المخزون حسب المنتج</h3><table><thead><tr><th>المنتج</th><th>القسم</th><th>رصيد البداية</th><th>الوارد</th><th>المباع</th><th>المتاح</th><th>الحالة</th></tr></thead><tbody>{inventory.map(row => <tr key={row.name}><td>{row.name}</td><td>{row.category}</td><td>{row.opening}</td><td>{row.inbound}</td><td>{row.sold}</td><td className="font-orbitron">{row.available}</td><td><Status value={row.status} /></td></tr>)}</tbody></table></div><div className="admin-grid" style={{ marginTop: 18 }}><div className="panel"><h3>ملخص المخزون</h3><div className="summary-line"><span>إجمالي الوحدات المتاحة</span><b>147</b></div><div className="summary-line"><span>منتجات تحت حد التنبيه</span><b style={{ color: "#fbbf24" }}>2</b></div><div className="summary-line"><span>قيمة المخزون الحالية</span><b>8,420 $</b></div></div><div className="panel"><h3>تنبيه شراء</h3><p style={{ color: "#fbbf24", margin: 0 }}>مطحنة القهوة وحقيبة Urban Line تحتاجان إلى إعادة طلب.</p></div></div></>; }

function MovementReport() { return <><FilterBar onChange={() => undefined} /><div className="panel table-wrap"><h3>سجل حركة البيع</h3><table><thead><tr><th>التاريخ والوقت</th><th>رقم الطلب</th><th>المنتج</th><th>الكمية</th><th>قيمة البيع</th><th>العميل</th><th>القناة</th></tr></thead><tbody>{movement.map(row => <tr key={row.order}><td>{row.date}</td><td className="font-orbitron">{row.order}</td><td>{row.product}</td><td>{row.quantity}</td><td><Money value={row.amount} /></td><td>{row.customer}</td><td>{row.channel}</td></tr>)}</tbody></table></div><div className="panel" style={{ marginTop: 18 }}><h3>إجمالي حركة الفترة</h3><div className="summary-line"><span>عدد عمليات البيع</span><b>188 عملية</b></div><div className="summary-line"><span>الوحدات الخارجة</span><b>264 وحدة</b></div><div className="summary-line"><span>إجمالي قيمة الحركة</span><b>9,820 $</b></div></div></>; }

export default function AdminReportsPage() { const router = useRouter(); const [ready, setReady] = useState(false); const [active, setActive] = useState<ReportKey>("sales"); useEffect(() => { if (localStorage.getItem("nova-admin-auth") !== "1") router.replace("/admin"); else setReady(true); }, [router]); const exportReport = () => alert("تم تجهيز التقرير للتنزيل بصيغة CSV (تجريبي)"); const content = useMemo(() => active === "sales" ? <SalesReport /> : active === "promotions" ? <PromotionsReport /> : active === "top" ? <ProductRankReport direction="top" /> : active === "low" ? <ProductRankReport direction="low" /> : active === "inventory" ? <InventoryReport /> : <MovementReport />, [active]); if (!ready) return null; return <div className="admin-shell content-layer"><aside className="admin-sidebar"><div className="admin-brand"><a href="/admin" className="brand"><span className="brand-mark"><Zap size={17} fill="currentColor" /></span><strong>NOVA</strong><span>ADMIN</span></a></div><nav className="admin-nav"><a href="/admin">لوحة المعلومات</a><a href="/admin/products">المنتجات</a><a href="/admin/categories">الأقسام</a><a href="/admin/orders">الطلبات</a><a href="/admin/inventory">المخزون</a><a href="/admin/promotions">العروض</a><a href="/admin/customers">العملاء</a><a className="active" href="/admin/reports">التقارير</a><a href="/admin/settings">الإعدادات</a></nav></aside><section className="admin-main"><header className="admin-header"><div className="eyebrow" style={{ margin: 0 }}>مساحة الإدارة · تقارير تفصيلية</div></header><div className="admin-content"><ReportHeader title="التقارير" description="حلّل المبيعات والعروض والمخزون وحركة البيع من شاشة واحدة." onExport={exportReport} /><div className="report-tabs">{reports.map(([key, label, Icon]) => <button className={active === key ? "report-tab active" : "report-tab"} key={key} onClick={() => setActive(key)}><Icon size={17} />{label}</button>)}</div>{content}</div></section></div>; }
