"use client";
/* eslint-disable @next/next/no-html-link-for-pages, @next/next/no-img-element, react-hooks/set-state-in-effect */

import { useEffect, useMemo, useState } from "react";
import { ArrowLeft, Check, CircleHelp, Clock3, GitCompare as Compare, MessageCircle, PackageCheck, Search, Sparkles, Star, Truck, X } from "lucide-react";
import { usePathname, useRouter } from "next/navigation";

type CustomerProduct = { id: number; name: string; slug: string; price: number; source: string; rating: number; stock: number; image: string };
const products: CustomerProduct[] = [
  { id: 1, name: "سماعات لاسلكية Auralite", slug: "auralite-wireless", price: 49, source: "MediaMarkt · ألمانيا", rating: 4.9, stock: 8, image: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=300&q=80" },
  { id: 2, name: "مصباح طاولة نوردك", slug: "nordic-table-lamp", price: 34, source: "IKEA Europe · السويد", rating: 4.7, stock: 14, image: "https://images.unsplash.com/photo-1507473885765-e6ed057f782c?auto=format&fit=crop&w=300&q=80" },
  { id: 3, name: "حقيبة ظهر Urban Line", slug: "urban-line-backpack", price: 58, source: "Zalando · ألمانيا", rating: 4.8, stock: 5, image: "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&w=300&q=80" },
  { id: 4, name: "طقم عناية بالبشرة Lumina", slug: "lumina-skin-set", price: 41, source: "Douglas · فرنسا", rating: 4.6, stock: 19, image: "https://images.unsplash.com/photo-1556228578-8c89e6adf883?auto=format&fit=crop&w=300&q=80" },
];
const offers = ["شحن مجاني للطلبات فوق 50 $", "خصم 20% على اختيارات الصيف", "منتجات أوروبية أصلية تصل إليك جديدة"];

function money(value: number, currency: string) { if (currency === "SYP") return `${Math.round(value * 13000).toLocaleString("en-US")} ل.س`; if (currency === "EUR") return `${(value * .92).toFixed(2)} €`; return `${value.toFixed(2)} $`; }

function SearchAssistant({ onClose }: { onClose: () => void }) { const [query, setQuery] = useState(""); const results = products.filter(product => !query || `${product.name} ${product.source}`.toLowerCase().includes(query.toLowerCase())); return <div className="customer-overlay"><div className="customer-modal"><div className="customer-modal-head"><div><span className="eyebrow">بحث ذكي</span><h2>ما الذي تبحث عنه؟</h2></div><button className="icon-btn" onClick={onClose} aria-label="إغلاق"><X size={19} /></button></div><div className="customer-search-input"><Search size={18} /><input autoFocus placeholder="اسم المنتج أو العلامة أو البلد" value={query} onChange={e => setQuery(e.target.value)} /></div><div className="customer-suggestions">{results.map(product => <a className="customer-suggestion" href={`/product/${product.slug}`} key={product.id}><img src={product.image} alt="" /><span><b>{product.name}</b><small>{product.source} · {money(product.price, "USD")}</small></span><ArrowLeft size={15} /></a>)}</div>{!results.length && <div className="empty">لا توجد نتائج مطابقة.</div>}<div className="customer-search-hints"><span>اقتراحات سريعة:</span><button onClick={() => setQuery("سماعات")}>سماعات</button><button onClick={() => setQuery("منزل")}>المنزل</button><button onClick={() => setQuery("ألمانيا")}>ألمانيا</button></div></div></div>; }

function CompareAssistant({ onClose }: { onClose: () => void }) { const [selected, setSelected] = useState<number[]>([1, 3]); const [currency, setCurrency] = useState("USD"); const toggle = (id: number) => setSelected(items => items.includes(id) ? items.filter(item => item !== id) : items.length < 3 ? [...items, id] : items); const selectedProducts = products.filter(product => selected.includes(product.id)); return <div className="customer-overlay"><div className="customer-modal compare-modal"><div className="customer-modal-head"><div><span className="eyebrow">اختيار أذكى</span><h2>قارن المنتجات</h2></div><button className="icon-btn" onClick={onClose} aria-label="إغلاق"><X size={19} /></button></div><p className="customer-muted">اختر حتى 3 منتجات لمقارنة السعر والمصدر والتقييم والمخزون.</p><div className="compare-picker">{products.map(product => <button className={selected.includes(product.id) ? "compare-product selected" : "compare-product"} key={product.id} onClick={() => toggle(product.id)}><img src={product.image} alt="" /><span>{product.name}</span>{selected.includes(product.id) && <Check size={15} />}</button>)}</div><div className="compare-table">{selectedProducts.map(product => <div className="compare-column" key={product.id}><img src={product.image} alt={product.name} /><b>{product.name}</b><span>{money(product.price, currency)}</span><small><Star size={13} fill="currentColor" /> {product.rating}</small><small>{product.source}</small><small style={{ color: product.stock < 6 ? "#fbbf24" : "#63e6be" }}>{product.stock < 6 ? `بقيت ${product.stock} قطع` : "متوفر للشحن"}</small></div>)}</div><div className="customer-modal-footer"><label>عرض الأسعار بـ <select value={currency} onChange={e => setCurrency(e.target.value)}><option value="USD">USD $</option><option value="SYP">SYP ل.س</option><option value="EUR">EUR €</option></select></label><a className="primary-btn" href={selectedProducts[0] ? `/product/${selectedProducts[0].slug}` : "/category/electronics"}>عرض المنتج <ArrowLeft size={16} /></a></div></div></div>; }

function RecentProducts({ items, onClose }: { items: CustomerProduct[]; onClose: () => void }) { return <div className="customer-recent"><div className="customer-recent-head"><span><Clock3 size={15} /> شوهد مؤخراً</span><button onClick={onClose} aria-label="إخفاء"><X size={15} /></button></div><div className="customer-recent-list">{items.slice(0, 3).map(product => <a href={`/product/${product.slug}`} key={product.id}><img src={product.image} alt="" /><span><b>{product.name}</b><small>{money(product.price, "USD")}</small></span></a>)}</div></div>; }

export default function CustomerEnhancements() { const pathname = usePathname(); const router = useRouter(); const [tool, setTool] = useState<"search" | "compare" | null>(null); const [showRecent, setShowRecent] = useState(true); const [recent, setRecent] = useState<CustomerProduct[]>([]); const [currency, setCurrency] = useState("USD"); const [offerIndex, setOfferIndex] = useState(0); const currentProduct = useMemo(() => { const slug = pathname.split("/").pop(); return pathname.startsWith("/product/") ? products.find(product => product.slug === slug) : undefined; }, [pathname]); useEffect(() => { const saved = localStorage.getItem("nova-recent-products"); const initial = saved ? JSON.parse(saved) as number[] : []; if (currentProduct) { const ids = [currentProduct.id, ...initial.filter(id => id !== currentProduct.id)].slice(0, 4); localStorage.setItem("nova-recent-products", JSON.stringify(ids)); setRecent(ids.map(id => products.find(product => product.id === id)).filter(Boolean) as CustomerProduct[]); } else setRecent(initial.map(id => products.find(product => product.id === id)).filter(Boolean) as CustomerProduct[]); const storedCurrency = localStorage.getItem("nova-currency") || "USD"; setCurrency(storedCurrency); }, [currentProduct, pathname]); useEffect(() => { const timer = window.setInterval(() => setOfferIndex(index => (index + 1) % offers.length), 5000); return () => window.clearInterval(timer); }, []); if (pathname.startsWith("/admin")) return null; const changeCurrency = (value: string) => { localStorage.setItem("nova-currency", value); setCurrency(value); window.location.reload(); }; return <><div className="customer-offer-ticker"><span><Sparkles size={14} /> {offers[offerIndex]}</span><a href="/category/offers">اكتشف العروض <ArrowLeft size={14} /></a></div><div className="customer-tools"><button onClick={() => setTool("search")} aria-label="بحث ذكي"><Search size={18} /></button><button onClick={() => setTool("compare")} aria-label="مقارنة المنتجات"><Compare size={18} /></button><button onClick={() => changeCurrency(currency === "USD" ? "SYP" : currency === "SYP" ? "EUR" : "USD")} aria-label="تبديل العملة"><span className="currency-mini">{currency === "USD" ? "$" : currency === "SYP" ? "ل.س" : "€"}</span></button><button onClick={() => router.push("https://wa.me/963944000000")} aria-label="تواصل سريع"><MessageCircle size={18} /></button></div><div className="customer-benefits"><span><Truck size={15} /> شحن خلال 48 ساعة</span><span><PackageCheck size={15} /> إرجاع خلال 14 يوماً</span><span><CircleHelp size={15} /> دعم مباشر</span></div>{showRecent && recent.length > 0 && !tool && <RecentProducts items={recent} onClose={() => setShowRecent(false)} />}{tool === "search" && <SearchAssistant onClose={() => setTool(null)} />}{tool === "compare" && <CompareAssistant onClose={() => setTool(null)} />}</>; }
