"use client";
/* eslint-disable @next/next/no-html-link-for-pages, @next/next/no-img-element, @typescript-eslint/no-unused-expressions */

import { useEffect, useMemo, useRef, useState } from "react";
import { AnimatePresence, motion } from "framer-motion";
import {
  ArrowLeft, ArrowUpRight, BarChart3, Bell, Box, Check, CircleUserRound, CreditCard, Heart,
  Home, LayoutDashboard, LogOut, Package, Pencil, Plus, Search, Settings, ShoppingBag,
  ShoppingCart, SlidersHorizontal, Sparkles, Store, Tag, Users, Zap,
} from "lucide-react";
import { usePathname, useRouter } from "next/navigation";

type Product = { id: number; name: string; slug: string; category: string; source: string; country: string; price: number; oldPrice: number; stock: number; rating: number; image: string; badge?: string; description: string; specs: [string, string][] };
type Order = { id: string; customer: string; date: string; total: number; status: string; items: number };

const image = (id: string) => `https://images.unsplash.com/${id}?auto=format&fit=crop&w=900&q=85`;
const products: Product[] = [
  { id: 1, name: "سماعات لاسلكية Auralite", slug: "auralite-wireless", category: "إلكترونيات", source: "MediaMarkt", country: "ألمانيا", price: 49, oldPrice: 69, stock: 8, rating: 4.9, badge: "الأكثر مبيعاً", image: image("photo-1505740420928-5e560c06d30e"), description: "صوت غامر وتصميم خفيف للاستخدام اليومي. منتج أوروبي أصلي يصل إليك جديداً بعلبته.", specs: [["البطارية", "32 ساعة"], ["الاتصال", "Bluetooth 5.3"], ["اللون", "أسود ليلي"]] },
  { id: 2, name: "مصباح طاولة نوردك", slug: "nordic-table-lamp", category: "المنزل", source: "IKEA Europe", country: "السويد", price: 34, oldPrice: 48, stock: 14, rating: 4.7, badge: "جديد", image: image("photo-1507473885765-e6ed057f782c"), description: "إضاءة هادئة بلمسة اسكندنافية، قطعة أنيقة للمكتب أو طاولة النوم.", specs: [["الخامة", "معدن مطلي"], ["القدرة", "12W LED"], ["الضمان", "سنتان"]] },
  { id: 3, name: "حقيبة ظهر Urban Line", slug: "urban-line-backpack", category: "أزياء", source: "Zalando", country: "ألمانيا", price: 58, oldPrice: 82, stock: 5, rating: 4.8, badge: "خصم 29%", image: image("photo-1553062407-98eeb64c6a62"), description: "حقيبة عملية بخامات متينة وحجرة مخصصة للحاسوب المحمول.", specs: [["السعة", "22 لتر"], ["الخامة", "قماش معاد التدوير"], ["المقاس", "45 × 30 سم"]] },
  { id: 4, name: "طقم عناية بالبشرة Lumina", slug: "lumina-skin-set", category: "العناية", source: "Douglas", country: "فرنسا", price: 41, oldPrice: 59, stock: 19, rating: 4.6, badge: "جديد", image: image("photo-1556228578-8c89e6adf883"), description: "روتين عناية يومي لطيف بمكونات مختارة من علامات أوروبية موثوقة.", specs: [["القطع", "3 منتجات"], ["النوع", "مناسب للبشرة الحساسة"], ["المصدر", "فرنسا"]] },
  { id: 5, name: "مطحنة قهوة Barista Pro", slug: "barista-coffee-grinder", category: "المنزل", source: "Otto", country: "ألمانيا", price: 76, oldPrice: 99, stock: 3, rating: 4.9, badge: "الأكثر مبيعاً", image: image("photo-1495474472287-4d71bcdd2085"), description: "طحن دقيق وقابل للتعديل لمحبي القهوة المختصة في المنزل.", specs: [["الإعدادات", "24 مستوى"], ["السعة", "250 غ"], ["القدرة", "150W"]] },
  { id: 6, name: "حذاء رياضي Cloud Move", slug: "cloud-move-shoes", category: "رياضة", source: "Decathlon", country: "فرنسا", price: 62, oldPrice: 88, stock: 12, rating: 4.8, image: image("photo-1542291026-7eec264c27ff"), description: "خفة وراحة للحركة اليومية والتمارين الخفيفة.", specs: [["النعل", "وسادة امتصاص"], ["الوزن", "240 غ"], ["المقاسات", "38 - 45"]] },
  { id: 7, name: "طقم تنظيم الأطفال MiniBox", slug: "minibox-organizer", category: "أطفال", source: "Lidl Europe", country: "هولندا", price: 27, oldPrice: 39, stock: 9, rating: 4.5, badge: "عرض", image: image("photo-1587654780291-39c9404d746b"), description: "صناديق ملونة وآمنة لترتيب ألعاب الأطفال بسهولة.", specs: [["القطع", "4 صناديق"], ["الخامة", "بلاستيك آمن"], ["العمر", "3 سنوات+"]] },
  { id: 8, name: "ساعة حائط Minimal", slug: "minimal-wall-clock", category: "المنزل", source: "Maisons du Monde", country: "فرنسا", price: 31, oldPrice: 44, stock: 16, rating: 4.4, image: image("photo-1563861826100-9cb868fdbe1c"), description: "تفصيل بسيط يمنح جدارك حضوراً هادئاً وعصرياً.", specs: [["القطر", "32 سم"], ["الآلة", "كوارتز صامت"], ["اللون", "أبيض وأسود"]] },
];
const categories = [
  ["إلكترونيات", "◈", "electronics"], ["أدوات منزلية", "⌂", "home"], ["أزياء", "◌", "fashion"], ["أطفال", "✦", "kids"], ["العناية", "✧", "care"], ["رياضة", "↗", "sport"],
];
const orders: Order[] = [
  { id: "NV-1048", customer: "ليان أحمد", date: "06 أغسطس 2026", total: 132, status: "قيد المعالجة", items: 3 },
  { id: "NV-1047", customer: "عمر خليل", date: "06 أغسطس 2026", total: 76, status: "تم الشحن", items: 1 },
  { id: "NV-1046", customer: "سارة يوسف", date: "05 أغسطس 2026", total: 214, status: "مكتمل", items: 4 },
  { id: "NV-1045", customer: "محمد حسان", date: "05 أغسطس 2026", total: 49, status: "مكتمل", items: 1 },
  { id: "NV-1044", customer: "نور الحلبي", date: "04 أغسطس 2026", total: 93, status: "قيد المراجعة", items: 2 },
];

function formatPrice(value: number) { const currency = typeof window !== "undefined" ? localStorage.getItem("nova-currency") || "USD" : "USD"; if (currency === "SYP") return `${Math.round(value * 13000).toLocaleString("en-US")} ل.س`; if (currency === "EUR") return `${(value * .92).toFixed(2)} €`; return `$${value.toLocaleString("en-US", { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`; }
function go(router: ReturnType<typeof useRouter>, href: string) { router.push(href); }

function ParticleCanvas() {
  const ref = useRef<HTMLCanvasElement>(null);
  useEffect(() => {
    const canvas = ref.current; if (!canvas) return;
    const ctx = canvas.getContext("2d"); if (!ctx) return;
    let frame = 0; let raf = 0;
    const reduce = window.matchMedia("(prefers-reduced-motion: reduce)");
    const dots = Array.from({ length: window.innerWidth < 700 ? 42 : 105 }, (_, i) => ({ x: Math.random(), y: Math.random(), vx: (Math.random()-.5)*.00035, vy: (Math.random()-.5)*.00035, r: i % 7 === 0 ? 1.7 : 1, hue: i % 3 }));
    const resize = () => { canvas.width = window.innerWidth * devicePixelRatio; canvas.height = window.innerHeight * devicePixelRatio; canvas.style.width = `${window.innerWidth}px`; canvas.style.height = `${window.innerHeight}px`; ctx.setTransform(devicePixelRatio,0,0,devicePixelRatio,0,0); };
    const render = () => {
      const w = window.innerWidth, h = window.innerHeight; frame += 1; ctx.clearRect(0,0,w,h);
      dots.forEach((dot, i) => { if (!reduce.matches) { dot.x += dot.vx; dot.y += dot.vy; } if (dot.x < 0) dot.x=1; if (dot.x > 1) dot.x=0; if (dot.y < 0) dot.y=1; if (dot.y > 1) dot.y=0; const pulse = .35 + Math.sin(frame*.018+i)*.18; const colors = ["0,240,255","168,85,247","236,72,153"]; ctx.fillStyle=`rgba(${colors[dot.hue]},${pulse})`; ctx.beginPath(); ctx.arc(dot.x*w,dot.y*h,dot.r,0,Math.PI*2); ctx.fill(); });
      dots.forEach((a, i) => dots.slice(i+1).forEach((b) => { const dx=(a.x-b.x)*w, dy=(a.y-b.y)*h, d=Math.sqrt(dx*dx+dy*dy); if(d<115){ctx.strokeStyle=`rgba(94,160,220,${(1-d/115)*.12})`;ctx.lineWidth=1;ctx.beginPath();ctx.moveTo(a.x*w,a.y*h);ctx.lineTo(b.x*w,b.y*h);ctx.stroke();} }));
      if (!document.hidden && !reduce.matches) raf = requestAnimationFrame(render);
    };
    const visibility = () => { if (!document.hidden && !reduce.matches) { cancelAnimationFrame(raf); raf=requestAnimationFrame(render); } };
    resize(); render(); window.addEventListener("resize",resize); document.addEventListener("visibilitychange",visibility);
    return () => { cancelAnimationFrame(raf); window.removeEventListener("resize",resize); document.removeEventListener("visibilitychange",visibility); };
  }, []);
  return <canvas ref={ref} className="canvas-bg" aria-hidden="true" />;
}

function Background() { return <><ParticleCanvas /><span className="orb orb-a" /><span className="orb orb-b" /><span className="orb orb-c" /></>; }

function Navbar({ cartCount, wishlistCount }: { cartCount: number; wishlistCount: number }) {
  const router = useRouter(); const pathname = usePathname();
  return <>
    <header className="topbar"><div className="container topbar-inner">
      <a href="/" className="brand"><span className="brand-mark"><Zap size={19} fill="currentColor" /></span><strong>NOVA</strong><span>MARKET</span></a>
      <nav className="nav-links"><a className={pathname === "/" ? "active" : ""} href="/">الرئيسية</a><a href="/category/electronics">الأقسام</a><a href="/category/offers">العروض</a><a href="/account">حسابي</a></nav>
      <div className="top-actions"><button className="icon-btn" aria-label="البحث" onClick={() => go(router,"/search")}><Search size={19} /></button><button className="icon-btn" aria-label="المفضلة" onClick={() => go(router,"/wishlist")}><Heart size={19} /><span className="badge">{wishlistCount}</span></button><button className="icon-btn" aria-label="السلة" onClick={() => go(router,"/cart")}><ShoppingCart size={19} /><span className="badge">{cartCount}</span></button><button className="avatar-btn" aria-label="لوحة الإدارة" onClick={() => go(router,"/admin")}><CircleUserRound size={20} /></button></div>
    </div></header>
    <nav className="mobile-nav"><a className={pathname === "/" ? "active" : ""} href="/"><Home size={19}/><span>الرئيسية</span></a><a href="/category/electronics"><Store size={19}/><span>الأقسام</span></a><a href="/cart"><ShoppingCart size={19}/><span>السلة {cartCount ? `(${cartCount})` : ""}</span></a><a href="/account"><CircleUserRound size={19}/><span>حسابي</span></a></nav>
  </>;
}

function ProductCard({ product, onCart, wished, onWish }: { product: Product; onCart: (p: Product) => void; wished: boolean; onWish: (p: Product) => void }) {
  return <motion.article className="product-card" initial={{ opacity: 0, y: 14 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true, margin: "-40px" }}>
    <a href={`/product/${product.slug}`}><div className="product-image"><img src={product.image} alt={product.name} loading="lazy" />{product.badge && <span className="status status-pink" style={{ position: "absolute", top: 12, right: 12 }}>{product.badge}</span>}<div className="product-overlay"><button type="button" className="round-btn" aria-label="إضافة للمفضلة" onClick={(e) => { e.preventDefault(); onWish(product); }}><Heart size={18} fill={wished ? "currentColor" : "none"} /></button><button type="button" className="round-btn" aria-label="إضافة للسلة" onClick={(e) => { e.preventDefault(); onCart(product); }}><ShoppingCart size={18} /></button></div></div></a>
    <div className="product-meta"><div className="product-source">{product.country} · {product.source}</div><a className="product-name" href={`/product/${product.slug}`}>{product.name}</a><div className="product-bottom"><div className="product-price">{formatPrice(product.price)}<del>{formatPrice(product.oldPrice)}</del></div><span className="rating">★ {product.rating}</span></div></div>
  </motion.article>;
}

function HomePage({ onCart, wished, onWish }: { onCart: (p: Product) => void; wished: Set<number>; onWish: (p: Product) => void }) {
  const router = useRouter();
  return <main className="content-layer"><section className="hero"><div className="container hero-grid"><div><div className="eyebrow">تجربة تسوق مختلفة</div><h1>مختارات <span className="gradient-text">أوروبية</span><br />تصل إليك جديدة.</h1><p className="hero-copy">منتجات أصلية من أفضل المتاجر الأوروبية، نختارها بعناية ونقدمها لك بثقة ووضوح.</p><div className="actions"><button className="primary-btn" onClick={() => go(router,"/category/electronics")}>استكشف المنتجات <ArrowLeft size={18}/></button><button className="secondary-btn" onClick={() => go(router,"/category/offers")}>شاهد العروض</button></div></div><div className="hero-visual"><span className="halo" /><div className="hero-product"><img src={products[0].image} alt="سماعات Auralite" /></div><div className="price-float"><small>اختيار هذا الأسبوع</small><b>{formatPrice(products[0].price)}</b><del>{formatPrice(products[0].oldPrice)}</del></div></div></div></section>
    <section className="section" style={{ paddingTop: 30 }}><div className="container stats-grid"><div className="stat"><div className="stat-value">2.4<span>k</span></div><div className="stat-label">منتج مختار</div></div><div className="stat"><div className="stat-value">98<span>%</span></div><div className="stat-label">رضا العملاء</div></div><div className="stat"><div className="stat-value">18<span>+</span></div><div className="stat-label">علامة أوروبية</div></div><div className="stat"><div className="stat-value">48<span>h</span></div><div className="stat-label">شحن سريع</div></div></div></section>
    <section className="section"><div className="container"><div className="section-head"><div><div className="section-kicker">اكتشف عالمك</div><h2 className="section-title">تسوق حسب القسم</h2></div><a href="/category/electronics" className="text-link">كل الأقسام <ArrowLeft size={16}/></a></div><div className="category-row">{categories.map(([name, icon, slug]) => <a className="category-chip" key={slug} href={`/category/${slug}`}><span className="category-icon">{icon}</span><span>{name}</span></a>)}</div></div></section>
    <section className="section" style={{ paddingTop: 20 }}><div className="container"><div className="section-head"><div><div className="section-kicker">وصول حديثاً</div><h2 className="section-title">قطع تستحق أن تراها</h2><p className="section-note">مختارات جديدة وصلت هذا الأسبوع من مصادرنا الأوروبية.</p></div><a href="/category/new" className="text-link">عرض الكل <ArrowLeft size={16}/></a></div><div className="product-grid">{products.slice(0,4).map(p => <ProductCard key={p.id} product={p} onCart={onCart} wished={wished.has(p.id)} onWish={onWish} />)}</div></div></section>
    <section className="section"><div className="container"><div className="offer-banner"><div className="offer-content"><div className="section-kicker">عرض محدود · ينتهي قريباً</div><h3>خصم يصل إلى <span className="gradient-text">30%</span></h3><p>على اختيارات المنزل والعناية. جودة أوروبية، بسعر أذكى.</p><button className="primary-btn" onClick={() => go(router,"/category/offers")}>اكتشف العرض <ArrowUpRight size={17}/></button></div></div></div></section>
    <section className="section" style={{ paddingTop: 20 }}><div className="container"><div className="section-head"><div><div className="section-kicker">الأكثر طلباً</div><h2 className="section-title">اختيارات المجتمع</h2></div></div><div className="product-grid">{products.slice(4,8).map(p => <ProductCard key={p.id} product={p} onCart={onCart} wished={wished.has(p.id)} onWish={onWish} />)}</div></div></section>
    <Footer /></main>;
}

function Footer() { return <footer className="footer content-layer"><div className="container footer-inner"><a href="/" className="brand"><span className="brand-mark"><Zap size={17} fill="currentColor" /></span><strong>NOVA</strong><span>MARKET</span></a><span>منتجات أوروبية أصلية، تصل إليك بثقة.</span><span>© 2026 NOVA MARKET</span></div></footer>; }

function CategoryPage({ onCart, wished, onWish }: { onCart: (p: Product) => void; wished: Set<number>; onWish: (p: Product) => void }) {
  const pathname = usePathname(); const slug = pathname.split("/").pop() || ""; const [search, setSearch] = useState(""); const [sort, setSort] = useState("new");
  const title = slug === "offers" ? "عروض لا تفوّت" : slug === "new" ? "وصل حديثاً" : categories.find(c => c[2] === slug)?.[0] || "كل المنتجات";
  const list = useMemo(() => products.filter(p => (!search || p.name.includes(search) || p.source.includes(search)) && (slug === "offers" ? p.oldPrice > p.price : slug === "new" ? p.id <= 4 : !slug || slug === "electronics" || p.category === title)).sort((a,b) => sort === "price" ? a.price-b.price : sort === "rating" ? b.rating-a.rating : b.id-a.id), [search, slug, sort, title]);
  return <main className="content-layer"><div className="page-head"><div className="container"><div className="eyebrow">مجموعة نوفا</div><h1>{title}</h1><p>{list.length} منتجات مختارة بعناية من شركائنا الأوروبيين.</p></div></div><div className="container"><div className="toolbar"><div className="toolbar-group"><div style={{ position: "relative" }}><Search size={17} style={{ position: "absolute", top: 14, right: 13, color: "var(--muted)" }}/><input className="field" style={{ paddingRight: 40 }} placeholder="ابحث في المنتجات" value={search} onChange={e => setSearch(e.target.value)} /></div><button className="secondary-btn"><SlidersHorizontal size={17}/> تصفية</button></div><select className="select" value={sort} onChange={e => setSort(e.target.value)}><option value="new">الأحدث</option><option value="price">الأقل سعراً</option><option value="rating">الأعلى تقييماً</option></select></div>{list.length ? <div className="product-grid" style={{ paddingBottom: 100 }}>{list.map(p => <ProductCard key={p.id} product={p} onCart={onCart} wished={wished.has(p.id)} onWish={onWish} />)}</div> : <div className="empty">لم نجد منتجات مطابقة. جرّب كلمة بحث أخرى.</div>}</div></main>;
}

function ProductPage({ onCart, wished, onWish }: { onCart: (p: Product) => void; wished: Set<number>; onWish: (p: Product) => void }) {
  const pathname = usePathname(); const slug = pathname.split("/").pop(); const product = products.find(p => p.slug === slug) || products[0]; const [qty, setQty] = useState(1);
  return <main className="content-layer"><div className="container detail-layout"><div><div className="detail-main-image"><img src={product.image} alt={product.name} /></div><div className="specs">{product.specs.map(([a,b]) => <div className="spec-row" key={a}><span>{a}</span><b>{b}</b></div>)}</div></div><div className="detail-info"><div className="eyebrow">{product.category} · {product.country}</div><h1>{product.name}</h1><div className="rating">★ {product.rating} <span style={{ color: "var(--muted)", marginInlineStart: 8 }}>({Math.round(product.rating*48)} مراجعة)</span></div><p className="detail-description">{product.description}</p><span className="source-tag"><Sparkles size={15}/> مصدر موثوق: {product.source} · {product.country}</span><div className="detail-price">{formatPrice(product.price)}<del>{formatPrice(product.oldPrice)}</del></div><div className="actions"><div className="qty"><button onClick={() => setQty(Math.max(1,qty-1))}>−</button><span>{qty}</span><button onClick={() => setQty(qty+1)}>+</button></div><button className="primary-btn" onClick={() => onCart(product)}>أضف إلى السلة <ShoppingCart size={17}/></button><button className={`round-btn ${wished.has(product.id) ? "active" : ""}`} onClick={() => onWish(product)}><Heart size={19} fill={wished.has(product.id) ? "currentColor" : "none"}/></button></div><p style={{ color: product.stock < 5 ? "#fbbf24" : "#63e6be", fontSize: 13, marginTop: 20 }}>{product.stock < 5 ? `بقيت ${product.stock} قطع فقط` : "متوفر للشحن خلال 48 ساعة"}</p></div></div><section className="section" style={{ paddingTop: 20 }}><div className="container"><div className="section-head"><div><div className="section-kicker">قد يعجبك أيضاً</div><h2 className="section-title">اختيارات مشابهة</h2></div></div><div className="product-grid">{products.filter(p=>p.id!==product.id).slice(0,4).map(p=><ProductCard key={p.id} product={p} onCart={onCart} wished={wished.has(p.id)} onWish={onWish}/>)}</div></div></section></main>;
}

function CartPage({ cart, onCart, onRemove }: { cart: Product[]; onCart: (p: Product) => void; onRemove: (id: number) => void }) {
  const router = useRouter(); const subtotal = cart.reduce((sum,p)=>sum+p.price,0); return <main className="content-layer"><div className="page-head"><div className="container"><div className="eyebrow">مساحتك المختارة</div><h1>السلة</h1><p>{cart.length ? `${cart.length} منتجات جاهزة للخطوة التالية.` : "لم تضف أي منتج بعد."}</p></div></div><div className="container split-layout">{cart.length ? <><div className="panel"><h2>المنتجات المختارة</h2>{cart.map(p=><div className="cart-row" key={p.id}><img src={p.image} alt={p.name}/><div><h3>{p.name}</h3><p>{p.source} · {formatPrice(p.price)}</p></div><><div className="qty"><button onClick={()=>onRemove(p.id)}>−</button><span>1</span><button onClick={()=>onCart(p)}>+</button></div></></div>)}</div><aside className="panel"><h2>ملخص الطلب</h2><div className="summary-line"><span>المجموع الفرعي</span><b>{formatPrice(subtotal)}</b></div><div className="summary-line"><span>الشحن</span><b>مجاني</b></div><div className="summary-line"><span>الخصم</span><b style={{color:"#63e6be"}}>− {formatPrice(Math.round(subtotal*.1))}</b></div><div className="summary-total"><span>الإجمالي</span><strong>{formatPrice(Math.round(subtotal*.9))}</strong></div><button className="primary-btn" style={{width:"100%", marginTop:24}} onClick={()=>go(router,"/checkout")}>متابعة إلى الدفع <ArrowLeft size={17}/></button></aside></> : <div className="empty" style={{gridColumn:"1/-1"}}><ShoppingBag size={34} style={{margin:"0 auto 15px", color:"var(--cyan)"}}/><p>ابدأ باختيار شيء يناسبك.</p><button className="primary-btn" onClick={()=>go(router,"/category/electronics")}>استكشف المنتجات</button></div>}</div></main>;
}

function WishlistPage({ wished, onCart, onWish }: { wished: Set<number>; onCart: (p: Product) => void; onWish: (p: Product) => void }) { const list = products.filter(p=>wished.has(p.id)); return <main className="content-layer"><div className="page-head"><div className="container"><div className="eyebrow">محفوظاتك</div><h1>المفضلة</h1><p>كل ما لفت انتباهك، في مكان واحد.</p></div></div><div className="container" style={{padding:"40px 0 100px"}}>{list.length ? <div className="product-grid">{list.map(p=><ProductCard key={p.id} product={p} onCart={onCart} wished onWish={onWish}/>)}</div> : <div className="empty">لم تحفظ أي منتج بعد.</div>}</div></main>; }

function CheckoutPage({ cart }: { cart: Product[] }) { const router=useRouter(); const [done,setDone]=useState(false); const [step,setStep]=useState(1); if(done) return <main className="login-page content-layer"><div className="panel login-box" style={{textAlign:"center"}}><Check size={48} color="var(--cyan)" style={{margin:"0 auto"}}/><h1>تم تأكيد طلبك</h1><p>رقم الطلب <strong className="font-orbitron">NV-1052</strong></p><button className="primary-btn" onClick={()=>go(router,"/")}>العودة للرئيسية</button></div></main>; return <main className="content-layer"><div className="page-head"><div className="container"><div className="eyebrow">خطوة واحدة تفصلك</div><h1>إتمام الطلب</h1><p>الدفع تجريبي في هذه المرحلة، بدون أي عملية مالية حقيقية.</p></div></div><div className="container split-layout"><div className="panel"><div className="actions" style={{marginBottom:28}}>{["العنوان","الشحن","الدفع","التأكيد"].map((s,i)=><button key={s} className={step===i+1?"primary-btn":"secondary-btn"} style={{minHeight:40,padding:"0 12px",fontSize:12}} onClick={()=>setStep(i+1)}>{i+1}. {s}</button>)}</div>{step===1&&<div className="form-grid"><div className="form-group"><label>الاسم الكامل</label><input className="form-control" defaultValue="نبيل" /></div><div className="form-group"><label>رقم الهاتف</label><input className="form-control" placeholder="09xxxxxxxx" /></div><div className="form-group full"><label>العنوان</label><input className="form-control" placeholder="المدينة، الشارع، رقم البناء" /></div></div>}{step===2&&<div><h2>اختر طريقة الشحن</h2><button className="secondary-btn" style={{width:"100%",justifyContent:"space-between",marginBottom:10}}>شحن سريع · خلال 48 ساعة <strong>مجاني</strong></button><button className="secondary-btn" style={{width:"100%",justifyContent:"space-between"}}>استلام من نقطة نوفا <strong>مجاني</strong></button></div>}{step===3&&<div><h2>طريقة الدفع</h2><div className="empty"><CreditCard size={30} style={{margin:"0 auto 12px"}}/>الدفع عند الاستلام متاح حالياً</div></div>}{step===4&&<div><h2>راجع طلبك</h2><p style={{color:"var(--muted)"}}>كل شيء جاهز. اضغط تأكيد لإكمال الطلب التجريبي.</p></div>}<button className="primary-btn" style={{marginTop:28}} onClick={()=>step<4?setStep(step+1):setDone(true)}>{step<4?"التالي":"تأكيد الطلب"}<ArrowLeft size={17}/></button></div><aside className="panel"><h2>ملخص سريع</h2><div className="summary-line"><span>المنتجات</span><b>{cart.length}</b></div><div className="summary-total"><span>الإجمالي</span><strong>{formatPrice(Math.round(cart.reduce((s,p)=>s+p.price,0)*.9))}</strong></div></aside></div></main>; }

function AuthPage({ register=false }: { register?: boolean }) { const router=useRouter(); const [email,setEmail]=useState(""); const [password,setPassword]=useState(""); const submit=(e:React.FormEvent)=>{e.preventDefault(); go(router,email.includes("admin")?"/admin":"/");}; return <main className="login-page content-layer"><div className="panel login-box"><a href="/" className="brand"><span className="brand-mark"><Zap size={17} fill="currentColor"/></span><strong>NOVA</strong><span>MARKET</span></a><h1>{register?"أنشئ حسابك":"مرحباً بك مجدداً"}</h1><p>{register?"ابدأ رحلة اكتشاف المنتجات الأوروبية.":"سجّل دخولك لمتابعة طلباتك ومفضلاتك."}</p><form className="login-form" onSubmit={submit}>{register&&<input className="form-control" placeholder="الاسم الكامل" required/>}<input className="form-control" type="email" placeholder="البريد الإلكتروني" value={email} onChange={e=>setEmail(e.target.value)} required/><input className="form-control" type="password" placeholder="كلمة المرور" value={password} onChange={e=>setPassword(e.target.value)} required/><button className="primary-btn" type="submit">{register?"إنشاء الحساب":"تسجيل الدخول"}<ArrowLeft size={17}/></button></form><p className="hint">للتجربة: اكتب أي بريد للمتجر، أو استخدم كلمة <b>admin</b> داخل البريد لفتح لوحة الإدارة. <br/><a href={register?"/login":"/register"} className="text-link">{register?"لديك حساب؟ سجّل دخولك":"ليس لديك حساب؟ أنشئ حساباً"}</a></p></div></main>; }

function AccountPage() { const router=useRouter(); return <main className="content-layer"><div className="page-head"><div className="container"><div className="eyebrow">مساحتك في نوفا</div><h1>أهلاً، نبيل</h1><p>تابع طلباتك واحتفظ باختياراتك المفضلة.</p></div></div><div className="container section"><div className="stats-grid"><div className="stat"><div className="stat-value">12</div><div className="stat-label">طلباً مكتملًا</div></div><div className="stat"><div className="stat-value">3</div><div className="stat-label">طلبات قيد الشحن</div></div><div className="stat"><div className="stat-value">8</div><div className="stat-label">منتجات مفضلة</div></div><div className="stat"><div className="stat-value">420<span>€</span></div><div className="stat-label">إجمالي مشترياتك</div></div></div><div className="actions" style={{marginTop:35}}><button className="secondary-btn" onClick={()=>go(router,"/account/orders")}>طلباتي <ArrowLeft size={16}/></button><button className="secondary-btn" onClick={()=>go(router,"/account/addresses")}>عناويني</button><button className="secondary-btn" onClick={()=>go(router,"/account/returns")}>الاستبدال والإرجاع</button></div></div></main>; }

function AccountOrders() { return <main className="content-layer"><div className="page-head"><div className="container"><div className="eyebrow">حسابي</div><h1>طلباتي</h1><p>كل طلباتك في سجل واحد واضح.</p></div></div><div className="container section"><div className="panel table-wrap"><table><thead><tr><th>رقم الطلب</th><th>التاريخ</th><th>العناصر</th><th>الإجمالي</th><th>الحالة</th></tr></thead><tbody>{orders.slice(0,3).map(o=><tr key={o.id}><td className="font-orbitron">{o.id}</td><td>{o.date}</td><td>{o.items}</td><td>{formatPrice(o.total)}</td><td><span className="status status-green">{o.status}</span></td></tr>)}</tbody></table></div></div></main>; }

const adminNav = [["لوحة المعلومات", "/admin", LayoutDashboard], ["المنتجات", "/admin/products", Package], ["الطلبات", "/admin/orders", ShoppingBag], ["المخزون", "/admin/inventory", Box], ["العروض", "/admin/promotions", Tag], ["العملاء", "/admin/customers", Users], ["التقارير", "/admin/reports", BarChart3], ["الإعدادات", "/admin/settings", Settings]] as const;
function AdminShell({ children }: { children: React.ReactNode }) { const pathname=usePathname(); const router=useRouter(); return <div className="admin-shell content-layer"><aside className="admin-sidebar"><div className="admin-brand"><a href="/" className="brand"><span className="brand-mark"><Zap size={17} fill="currentColor"/></span><strong>NOVA</strong><span>ADMIN</span></a></div><nav className="admin-nav">{adminNav.map(([label,href,Icon])=><a className={pathname===href?"active":""} href={href} key={href}><Icon size={18}/>{label}</a>)}</nav><button className="secondary-btn" style={{width:"100%",marginTop:28}} onClick={()=>go(router,"/")}><LogOut size={16}/> العودة للمتجر</button></aside><section className="admin-main"><header className="admin-header"><div className="eyebrow" style={{margin:0}}>مساحة الإدارة</div><div style={{display:"flex",gap:8}}><button className="icon-btn"><Bell size={18}/></button><button className="avatar-btn"><CircleUserRound size={20}/></button></div></header>{children}</section></div>; }

function AdminDashboard() { const bars=[43,62,55,76,50,83,66,91,70,87,76,95,72,84,60,78,92,88,94,81]; return <div className="admin-content"><div className="admin-title"><div><h1>لوحة المعلومات</h1><p>نظرة سريعة على أداء متجرك اليوم.</p></div><button className="primary-btn"><Plus size={17}/> إضافة منتج</button></div><div className="kpi-grid"><div className="panel kpi" style={{"--accent":"var(--cyan)"} as React.CSSProperties}><div className="kpi-label">مبيعات اليوم</div><div className="kpi-value">2,840 €</div><div className="kpi-change">↑ 18.4% عن الأمس</div></div><div className="panel kpi" style={{"--accent":"var(--purple)"} as React.CSSProperties}><div className="kpi-label">إجمالي الطلبات</div><div className="kpi-value">128</div><div className="kpi-change">↑ 12.6% هذا الشهر</div></div><div className="panel kpi" style={{"--accent":"var(--pink)"} as React.CSSProperties}><div className="kpi-label">متوسط السلة</div><div className="kpi-value">64 €</div><div className="kpi-change">↑ 8.2% عن الأسبوع</div></div><div className="panel kpi" style={{"--accent":"var(--gold)"} as React.CSSProperties}><div className="kpi-label">عملاء جدد</div><div className="kpi-value">46</div><div className="kpi-change">↑ 21.5% هذا الأسبوع</div></div></div><div className="admin-grid"><div className="panel"><h3>المبيعات خلال 30 يوماً</h3><div className="chart">{bars.map((h,i)=><span className="bar" style={{"--height":`${h}%`} as React.CSSProperties} key={i}/>)}</div></div><div className="panel"><h3>الأكثر مبيعاً</h3>{products.slice(0,4).map((p,i)=><div className="cart-row" style={{gridTemplateColumns:"38px 1fr auto",padding:"10px 0"}} key={p.id}><img src={p.image} alt="" style={{width:38,height:38,borderRadius:8}}/><div><b style={{fontSize:13}}>{p.name}</b><p>{(44-i*5)} عملية بيع</p></div><span className="font-orbitron" style={{fontSize:12}}>{formatPrice(p.price)}</span></div>)}</div></div><div className="panel"><h3>آخر الطلبات</h3><div className="table-wrap"><table><thead><tr><th>الطلب</th><th>العميل</th><th>التاريخ</th><th>الإجمالي</th><th>الحالة</th></tr></thead><tbody>{orders.map(o=><tr key={o.id}><td className="font-orbitron">{o.id}</td><td>{o.customer}</td><td>{o.date}</td><td>{formatPrice(o.total)}</td><td><span className={`status ${o.status === "مكتمل" ? "status-green" : "status-orange"}`}>{o.status}</span></td></tr>)}</tbody></table></div></div></div>; }

function AdminTablePage({ type }: { type: string }) { const [query,setQuery]=useState(""); const title=type==="products"?"المنتجات":type==="orders"?"الطلبات":type==="inventory"?"إدارة المخزون":type==="customers"?"العملاء":type==="promotions"?"العروض والحملات":"التقارير"; const isProducts=type==="products"; const rows=isProducts?products.map(p=>({a:p.name,b:p.source,c:p.category,d:formatPrice(p.price),e:`${p.stock} قطعة`,f:p.stock<5?"منخفض":"متوفر"})):orders.map(o=>({a:o.id,b:o.customer,c:o.date,d:formatPrice(o.total),e:`${o.items} عناصر`,f:o.status})); const filtered=rows.filter(r=>Object.values(r).some(v=>v.toLowerCase().includes(query.toLowerCase()))); return <div className="admin-content"><div className="admin-title"><div><h1>{title}</h1><p>إدارة ومتابعة بيانات {title.toLowerCase()} من مكان واحد.</p></div>{isProducts&&<button className="primary-btn"><Plus size={17}/> منتج جديد</button>}</div><div className="panel"><div className="toolbar"><div className="toolbar-group"><div style={{position:"relative"}}><Search size={16} style={{position:"absolute",top:14,right:12,color:"var(--muted)"}}/><input className="field" style={{paddingRight:38}} placeholder="بحث سريع" value={query} onChange={e=>setQuery(e.target.value)}/></div><button className="secondary-btn"><SlidersHorizontal size={16}/> تصفية</button></div><button className="secondary-btn"><ArrowUpRight size={16}/> تصدير</button></div><div className="table-wrap"><table><thead><tr><th>{isProducts?"المنتج":"المرجع"}</th><th>{isProducts?"المصدر":"العميل"}</th><th>{isProducts?"القسم":"التاريخ"}</th><th>القيمة</th><th>التفاصيل</th><th>الحالة</th><th>إجراء</th></tr></thead><tbody>{filtered.map((r,i)=><tr key={i}><td>{r.a}</td><td>{r.b}</td><td>{r.c}</td><td>{r.d}</td><td>{r.e}</td><td><span className={`status ${r.f==="متوفر"||r.f==="مكتمل"?"status-green":"status-orange"}`}>{r.f}</span></td><td><button className="icon-btn" style={{width:34,height:34}}><Pencil size={15}/></button></td></tr>)}</tbody></table></div></div></div>; }

function AdminSettings() { return <div className="admin-content"><div className="admin-title"><div><h1>الإعدادات</h1><p>بيانات المتجر وطرق التواصل والشحن.</p></div><button className="primary-btn"><Check size={17}/> حفظ التغييرات</button></div><div className="panel"><div className="form-grid"><div className="form-group"><label>اسم المتجر</label><input className="form-control" defaultValue="NOVA MARKET"/></div><div className="form-group"><label>البريد الإلكتروني</label><input className="form-control" defaultValue="hello@novamarket.store"/></div><div className="form-group"><label>رسالة الترحيب</label><input className="form-control" defaultValue="مختارات أوروبية تصل إليك جديدة."/></div><div className="form-group"><label>سعر الشحن</label><input className="form-control" defaultValue="مجاني للطلبات فوق 50 €"/></div><div className="form-group full"><label>وصف المتجر</label><textarea className="form-control" defaultValue="نختار المنتجات الأوروبية الأصلية من شركاء موثوقين ونقدمها لك بوضوح وثقة."/></div></div></div></div>; }

function AdminPage() { const pathname=usePathname(); const sub=pathname.split("/")[2] || ""; return <AdminShell>{!sub?<AdminDashboard/>:sub==="settings"?<AdminSettings/>:<AdminTablePage type={sub}/>}</AdminShell>; }

export default function MarketApp() { const pathname=usePathname(); const [cart,setCart]=useState<Product[]>([products[0]]); const [wished,setWished]=useState<Set<number>>(new Set([3])); const [toast,setToast]=useState(""); useEffect(()=>{ if(!toast)return; const t=setTimeout(()=>setToast(""),2400); return()=>clearTimeout(t); },[toast]); const add=(p:Product)=>{setCart(prev=>[...prev,p]);setToast(`تمت إضافة ${p.name} إلى السلة`);}; const remove=(id:number)=>setCart(prev=>{const i=prev.findIndex(p=>p.id===id);if(i<0)return prev;const next=[...prev];next.splice(i,1);return next;}); const wish=(p:Product)=>setWished(prev=>{const n=new Set(prev);n.has(p.id)?n.delete(p.id):n.add(p.id);return n;}); const isAdmin=pathname.startsWith("/admin"); let page:React.ReactNode; if(isAdmin) page=<AdminPage/>; else if(pathname==="/"||pathname==="") page=<HomePage onCart={add} wished={wished} onWish={wish}/>; else if(pathname.startsWith("/category/")) page=<><Navbar cartCount={cart.length} wishlistCount={wished.size}/><CategoryPage onCart={add} wished={wished} onWish={wish}/></>; else if(pathname.startsWith("/product/")) page=<><Navbar cartCount={cart.length} wishlistCount={wished.size}/><ProductPage onCart={add} wished={wished} onWish={wish}/></>; else if(pathname==="/cart") page=<><Navbar cartCount={cart.length} wishlistCount={wished.size}/><CartPage cart={cart} onCart={add} onRemove={remove}/></>; else if(pathname==="/wishlist") page=<><Navbar cartCount={cart.length} wishlistCount={wished.size}/><WishlistPage wished={wished} onCart={add} onWish={wish}/></>; else if(pathname==="/checkout") page=<><Navbar cartCount={cart.length} wishlistCount={wished.size}/><CheckoutPage cart={cart}/></>; else if(pathname==="/login"||pathname==="/register") page=<AuthPage register={pathname==="/register"}/>; else if(pathname==="/account/orders") page=<><Navbar cartCount={cart.length} wishlistCount={wished.size}/><AccountOrders/></>; else if(pathname.startsWith("/account")) page=<><Navbar cartCount={cart.length} wishlistCount={wished.size}/><AccountPage/></>; else page=<><Navbar cartCount={cart.length} wishlistCount={wished.size}/><HomePage onCart={add} wished={wished} onWish={wish}/></>; return <div className="site-shell"><Background/>{page}<AnimatePresence>{toast&&<motion.div initial={{opacity:0,y:20}} animate={{opacity:1,y:0}} exit={{opacity:0,y:20}} style={{position:"fixed",zIndex:50,bottom:24,right:24,maxWidth:340,padding:"14px 18px",borderRadius:13,background:"#111329",border:"1px solid rgba(0,240,255,.35)",boxShadow:"0 12px 35px rgba(0,0,0,.35)",fontSize:13}}><Check size={16} color="var(--cyan)" style={{verticalAlign:"middle",marginInlineEnd:7}}/>{toast}</motion.div>}</AnimatePresence></div>; }
